# Generated by Django 3.2.7 on 2022-06-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('category', models.CharField(choices=[('bathnshampoo', '바스&샴푸'), ('oil', '오일'), ('lotion', '로션'), ('cream', '크림'), ('powderlotion', '파우더로션')], max_length=12, verbose_name='분류')),
                ('capacity', models.IntegerField(verbose_name='용량')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('photo', models.CharField(max_length=1000, verbose_name='상품이미지')),
                ('detail', models.CharField(max_length=1000, verbose_name='상세이미지')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('hashtags', models.ManyToManyField(blank=True, related_name='products', to='product.Hashtag')),
            ],
        ),
    ]
