# Generated by Django 3.2.7 on 2022-06-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='상세이미지'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hashtags',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='product.Hashtag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='상품이미지'),
        ),
    ]
