# Generated by Django 3.2.7 on 2022-06-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20220621_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='상세이미지'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='상품이미지'),
        ),
    ]
