# Generated by Django 3.2.7 on 2022-06-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='detail',
            new_name='detail_img',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='photo',
            new_name='product_img',
        ),
    ]
