# Generated by Django 3.2.7 on 2022-06-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20220622_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.Hashtag'),
        ),
    ]
