# Generated by Django 3.2.7 on 2022-06-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('바스 & 샴푸', '바스 & 샴푸'), ('오일', '오일'), ('로션', '로션'), ('크림', '크림'), ('파우더로션', '파우더로션')], max_length=12, verbose_name='분류'),
        ),
    ]
