# Generated by Django 3.2.7 on 2022-06-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail_img',
            field=models.ImageField(blank=True, null=True, upload_to='detail', verbose_name='상세이미지'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='상품이미지'),
        ),
    ]
