# Generated by Django 3.2.7 on 2022-07-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_created_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail_img',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail', verbose_name='썸네일이미지'),
        ),
    ]
