# Generated by Django 3.2.7 on 2022-06-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220616_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': '소셜', 'verbose_name_plural': '소셜'},
        ),
    ]
