# Generated by Django 3.2.7 on 2022-06-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_social_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'managed': False, 'verbose_name': '소셜', 'verbose_name_plural': '소셜'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_register',
            field=models.BooleanField(default=False, verbose_name='등록여부'),
        ),
    ]
