# Generated by Django 3.2.7 on 2022-06-17 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220616_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': '소셜', 'verbose_name_plural': '소셜'},
        ),
    ]
