# Generated by Django 3.2.7 on 2022-06-27 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20220624_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created',
            new_name='created_at',
        ),
    ]
