# Generated by Django 3.2.7 on 2022-07-04 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20220627_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasons', models.CharField(choices=[('아이디 변경(재가입)', '아이디 변경(재가입)'), ('낮은 구매 빈도', '낮은 구매 빈도'), ('서비스 및 고객지원 불만족', '서비스 및 고객지원 불만족'), ('타 브랜드 이용', '타 브랜드 이용'), ('기타', '기타')], max_length=20, verbose_name='탈퇴사유')),
                ('reason_others', models.TextField(max_length=1000, null=True, verbose_name='기타사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='탈퇴일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '회원탈퇴',
                'verbose_name_plural': '회원탈퇴',
            },
        ),
    ]
