# Generated by Django 3.2.7 on 2022-07-06 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_withdrawal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
