# Generated by Django 3.2.7 on 2022-07-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_delete_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='age_range',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profile_img',
            new_name='avatar',
        ),
    ]
