# Generated by Django 3.2.7 on 2022-07-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20220707_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agree_all_terms',
            field=models.BooleanField(default=False, verbose_name='약관전체동의'),
        ),
        migrations.AddField(
            model_name='user',
            name='marketing_terms',
            field=models.BooleanField(default=False, verbose_name='마케팅동의'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='이름'),
        ),
        migrations.AddField(
            model_name='user',
            name='private_info_terms',
            field=models.BooleanField(default=False, verbose_name='개인정보동의'),
        ),
        migrations.AddField(
            model_name='user',
            name='required_terms',
            field=models.BooleanField(default=False, verbose_name='필수약관동의'),
        ),
    ]
