# Generated by Django 3.2.7 on 2022-04-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Example",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=256, verbose_name="타이틀")),
                ("content", models.TextField(verbose_name="내용")),
                ("is_active", models.BooleanField(default=True, verbose_name="노출 여부")),
            ],
            options={
                "verbose_name": "Example",
                "verbose_name_plural": "Example",
            },
        ),
    ]
