# Generated by Django 3.2.7 on 2022-06-30 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_is_cancelled'),
        ('review', '0003_alter_photo_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order_product',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='order.orderproduct'),
            preserve_default=False,
        ),
    ]
