# Generated by Django 3.2.7 on 2022-06-30 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_is_cancelled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0012_rename_created_product_created_at'),
        ('review', '0004_review_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='review.review', verbose_name='리뷰'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='review.review', verbose_name='리뷰'),
        ),
        migrations.AlterField(
            model_name='review',
            name='order_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='order.orderproduct', verbose_name='주문-상품'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product', verbose_name='상품'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
    ]
