# Generated by Django 3.2.7 on 2022-07-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20220630_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_honest',
            field=models.BooleanField(default=False, verbose_name='솔직리뷰'),
        ),
    ]
