# Generated by Django 3.2.7 on 2022-06-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_shipping_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('신용카드', '신용카드')], max_length=4, verbose_name='결제수단'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_status',
            field=models.CharField(choices=[('결제완료', '결제완료'), ('결제취소', '결제취소')], max_length=9, verbose_name='결제상태'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('결제완료', '결제완료'), ('상품준비중', '상품준비중'), ('배송중', '배송중'), ('배송완료', '배송완료')], max_length=8, verbose_name='배송상태'),
        ),
    ]
