# Generated by Django 3.2.7 on 2022-06-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20220627_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='amount',
            new_name='quantity',
        ),
    ]
