# Generated by Django 3.2.7 on 2022-07-01 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20220701_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.IntegerField(default=27000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='상품가격'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='shipping_status',
            field=models.CharField(choices=[('결제완료', '결제완료'), ('상품준비중', '상품준비중'), ('배송중', '배송중'), ('배송완료', '배송완료')], default='결제완료', max_length=8, verbose_name='배송상태'),
            preserve_default=False,
        ),
    ]
