# Generated by Django 3.2.7 on 2022-07-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20220701_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address_detail',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='배송상세주소'),
        ),
    ]
