# Generated by Django 3.2.7 on 2022-07-01 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_shipping_address_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_paid',
            field=models.IntegerField(default=27000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='결제금액'),
            preserve_default=False,
        ),
    ]
