# Generated by Django 3.2.7 on 2022-07-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_orderproduct_unique_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pay_status',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='취소여부'),
        ),
    ]
