# Generated by Django 3.2.7 on 2022-07-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20220701_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='0000000000', max_length=10, unique=True, verbose_name='주문번호'),
        ),
    ]
