# Generated by Django 3.2.7 on 2022-07-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='imp_uid',
            field=models.CharField(max_length=30, null=True, verbose_name='결제번호'),
        ),
    ]
