# Generated by Django 3.2.7 on 2022-07-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_imp_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='imp_uid',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='결제번호'),
        ),
    ]
