# Generated by Django 3.2.7 on 2022-07-08 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_order_imp_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='환불금액'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_paid',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='결제금액'),
        ),
    ]
