# Generated by Django 3.2.7 on 2022-07-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_order_imp_uid'),
        ('order', '0015_auto_20220708_1508'),
    ]

    operations = [
    ]
