# Generated by Django 3.2.7 on 2022-07-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20220708_1508'),
        ('order', '0016_auto_20220708_1642'),
    ]

    operations = [
    ]
