# Generated by Django 3.2.7 on 2022-07-11 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_merge_0015_auto_20220708_1508_0016_auto_20220708_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_number',
            new_name='merchant_uid',
        ),
    ]
