# Generated by Django 3.2.7 on 2022-07-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_rename_order_number_order_merchant_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='merchant_uid',
            field=models.CharField(default='ORD000000-000000', max_length=16, unique=True, verbose_name='주문번호'),
        ),
    ]
